[features]
seeds = true
skip-lint = false
[programs.devnet]
scavenger_hunt = "Di2e9PAgcwGHdAJF6d5zxEXTj9KdDm8dWpmc6FcMoK1J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
